CREATE DATABASE if not exists crud;
CREATE TABLE crud.usuarios (
id INT(9) PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR(255) NOT NULL,
ape1 VARCHAR(255) NOT NULL,
ape2 VARCHAR(255) NOT NULL,
fechanac VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish2_ci;
