services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8

    container_name: mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

    volumes:
      - mongo_data:/data/db

    ports:
      - "27017:27017"

  phpmyadmin:
    container_name: phpmyadmin
    build: ./phpmyadmin

    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root

    ports:
      - "8081:80"

  mariadb:
    container_name: mariadb
    build: ./mariadb

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass

    ports:
      - "3316:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
  backend:
    container_name: uvicorn_python

    build: ./backend

    volumes:
      - ./projects:/projects

    ports:
      - "8000:8000"

    depends_on:
      - mongodb

    environment:
      DB_HOST: mongodb

  frontend:
    container_name: nginx_frontend

    build: ./frontend

    volumes:
      - ./projects:/usr/share/nginx/html:ro

    ports:
      - "8083:80"

    depends_on:
      - backend

volumes:
  mongo_data:
  mariadb_data:
